version: '3.8'

services:
  # Roteador 1
  router1:
    image: router
    build: ./routers
    container_name: router1
    environment:
      - ROUTER_ID=router1
      - LISTEN_PORT=5000
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      subnet1:
        ipv4_address: 10.0.1.1
      subnet2:
        ipv4_address: 10.0.2.1
      backbone:
        ipv4_address: 10.1.0.1

  # Roteador 2
  router2:
    image: router
    build: ./routers
    container_name: router2
    environment:
      - ROUTER_ID=router2
      - LISTEN_PORT=5000
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      subnet3:
        ipv4_address: 10.0.3.1
      subnet4:
        ipv4_address: 10.0.4.1
      backbone:
        ipv4_address: 10.1.0.2

  # Roteador 3
  router3:
    image: router
    build: ./routers
    container_name: router3
    environment:
      - ROUTER_ID=router3
      - LISTEN_PORT=5000
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      subnet5:
        ipv4_address: 10.0.5.1
      subnet6:
        ipv4_address: 10.0.6.1
      backbone:
        ipv4_address: 10.1.0.3

  # Hosts do Roteador 1
  host1a:
    image: redes2-host
    build: ./hosts
    container_name: host1a
    networks:
      subnet1:
        ipv4_address: 10.0.1.10

  host1b:
    image: redes2-host
    build: ./hosts
    container_name: host1b
    networks:
      subnet2:
        ipv4_address: 10.0.2.10

  # Hosts do Roteador 2
  host2a:
    image: redes2-host
    build: ./hosts
    container_name: host2a
    networks:
      subnet3:
        ipv4_address: 10.0.3.10

  host2b:
    image: redes2-host
    build: ./hosts
    container_name: host2b
    networks:
      subnet4:
        ipv4_address: 10.0.4.10

  # Hosts do Roteador 3
  host3a:
    image: redes2-host
    build: ./hosts
    container_name: host3a
    networks:
      subnet5:
        ipv4_address: 10.0.5.10

  host3b:
    image: redes2-host
    build: ./hosts
    container_name: host3b
    networks:
      subnet6:
        ipv4_address: 10.0.6.10

networks:
  # Redes locais de cada roteador
  subnet1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
  subnet2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
  subnet3:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.3.0/24
  subnet4:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.4.0/24
  subnet5:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.5.0/24
  subnet6:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.6.0/24
  
  # Rede backbone para interconexão dos roteadores
  backbone:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24